# Personalize your website info here
title:            Juraj Jakubik
tagline:          'Professional portfolio of Juraj Jakubik'
description:      'Portfolio and Blog for Juraj Jakubik'
url:              http://jurajjakubik.github.io
author:
  name:           'Juraj Jakubik'
  url:            https://www.linkedin.com/in/juraj-jakub%C3%ADk-0a6473127/

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
